- name: fetch Fabric Faults Info
  hosts: apic
  gather_facts: no
  vars_files:
          - vars/apic_vars.yml
  tasks:

  - name: Query APIC
    aci_rest:
     host: "{{ apic_ip }}"
     username: "{{ apic_username }}"
     password: "{{ apic_password }}"
     validate_certs: no
     method: get
     path: "{{ fabric_fault_api_path }}"
    delegate_to: localhost    
    register: query_result

  - name: Filter Query
    set_fact:
            fault_info: "{{ query_result | json_query(\"imdata[*].faultInst.attributes.{code: code, creationTime: created, description: descr, dn: dn, domain: domain, severity: severity, ack: ack}\") }}"
    
  - name: FAULT DETAILS
    debug:
     msg: 
      - "{{ fault_info }}"
      - "Critical Faults: {{ fault_info | regex_findall('critical') | length }}"
      - "Major Faults: {{ fault_info | regex_findall('major') | length }}"
      - "Minor Faults: {{ fault_info | regex_findall('minor') | length }}"
      - "Warnings: {{ fault_info | regex_findall('warning') | length }}"
      - "Cleared Faults: {{ fault_info | regex_findall('cleared') | length }}"
