- name: Fetch AES Details
  hosts: apic
  gather_facts: no
  vars_files:
          - vars/apic_vars.yml
  tasks: 

  - name: Query APIC
    aci_rest:
     host: "{{ apic_ip }}"
     username: "{{ apic_username }}"
     password: "{{ apic_password }}"
     validate_certs: no
     method: get
     path: "{{ aes_api_path }}"
    delegate_to: localhost    
    register: query_result
  - name: Filter Query
    set_fact: 
     AES_DETAILS: "{{ query_result | json_query(\"imdata[*].pkiExportEncryptionKey.attributes.{keyConfigured: keyConfigured, cryptedPassphrase: cryptedPassphrase, strongEncryptionEnabled: strongEncryptionEnabled}\")   }}" 
  - debug:
          var: AES_DETAILS
