- name: Fetch Firmware Details
  hosts: apic
  gather_facts: no
  vars_files:
          - vars/apic_vars.yml
  tasks: 

  - name: Query APIC
    aci_rest:
     host: "{{ apic_ip }}"
     username: "{{ apic_username }}"
     password: "{{ apic_password }}"
     validate_certs: no
     method: get
     path: "{{ phys_node_api_path }}"
    delegate_to: localhost    
    register: query_result

  - name: Filter Query
    set_fact:
            LEAF_DETAILS: "{{ query_result | json_query(\"imdata[*].fabricNode.attributes | [?role=='leaf'].{name: name, model: model, version: version}\") }}"
            SPINE_DETAILS: "{{ query_result | json_query(\"imdata[*].fabricNode.attributes | [?role=='spine'].{name: name, model: model, version: version}\") }}" 
            CONTROLLER_DETAILS: "{{ query_result | json_query(\"imdata[*].fabricNode.attributes | [?role=='controller'].{name: name , model: model, version: version}\") }}"
  - name: APIC  FIRMWARE DETAILS
    debug:
     var:  CONTROLLER_DETAILS

  - name: SPINE FIRMWARE DETAILS
    debug:
     var: SPINE_DETAILS

  - name: LEAF FIRMWARE DETAILS
    debug:
     var: LEAF_DETAILS

